[package]
name = "trojan"
version = "0.8.2"
authors = ["Hoping White <baihaoping@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
mio = { version = "0.8", features = ["net", "os-poll"] }
log = "0.4"
chrono = "0.4"
libc = "0.2"
rustls = "0.20"
rust-crypto = "0.2"
bytes = "1.1"
dns-lookup = "1.0"
cfg-if = "1.0"
webpki-roots = "0.22"
webpki = "0.22"
mio-extras = "2.0"
socket2 = "0.4"
rayon = "1.5"
rustls-pemfile = "0.2"
lazy_static = "1.4"
derive_more = "0.99"

[dependencies.fern]
version = "0.6"
features = ["reopen-03"]

[profile.release]
lto = true
